config/routes.rb
Rails.application.routes.draw do
  root 'records#index'
  resources :records
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

  def index
    @records = Record.all
  end

  def new
    @record = Record.new
  end

  def create
    Record.create(record_params)
    redirect_to root_path
  end

  private

  def record_params
    params.require(:record).permit(:name, :description, :title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Goldmine2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!-- <a class="navbar-brand" href="#">the goldmine</a> -->
  <%= link_to 'Duel of the iron mics', root_path, class: 'navbar-brand' %>

    </head>


  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <li class="nav-item">
      <!-- <a class="nav-link" href="#">Link</a> -->
      <%= link_to 'add', new_record_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>
&nbsp;
&nbsp;
<center><h3>Quoting the sharpest, and inspirational wordplay. Add ya lyrics, and wyze werdz</h3></center>



    <%= yield %>
  </body>
  coded by: @rt3l0 $tudi0
</html>

app/views/records/index.html.erb
<% @records.each do |record| %>
  <div class="booyah-box col-10 offset-1">
    <h1>Artist: <%= record.name %></h1>
    <i>Title: <%= record.title %></i><br /><br />
    <p>Lyric: %= record.description %></p><br />
  </div>
<% end %>

app/views/records/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>words of wisdom</h1>
  <%= simple_form_for @record do |f| %>
    <%= f.input :name %>
    <%= f.input :title %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>